project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Research & Projects
      - href: CV.qmd
        text: CV&Resume
    
  page-footer:
    right: "&copy; 2024, Ruibin Lyu"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
